# Generated by Django 3.0.2 on 2020-01-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunr', '0002_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='preview_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
